import { z } from 'zod';
import { DESIRED_FIELDS } from '../../utils/constants.js';

/**
 * Clarification checklist — generated by the AI after the user enters a
 * raw query. Each question is one of three shapes:
 *   - 'single'  → radio; `options` required.
 *   - 'multi'   → checkboxes; `options` required.
 *   - 'text'    → freeform string; `placeholder` optional.
 *
 * `rationale` is shown to the user so they know why answering matters —
 * they can still skip non-required questions.
 */
export const ClarificationQuestionTypeSchema = z.enum(['single', 'multi', 'text']);

export const ClarificationQuestionSchema = z.object({
  id: z.string().min(1).max(80),
  question: z.string().min(1).max(500),
  type: ClarificationQuestionTypeSchema,
  options: z.array(z.string().min(1).max(200)).max(12).optional(),
  required: z.boolean().default(false),
  placeholder: z.string().max(200).nullish(),
  rationale: z.string().max(300).nullish(),
});

export const ClarificationAnswerSchema = z.object({
  id: z.string().min(1).max(80),
  question: z.string().min(1).max(500),
  // Single / text → string; multi → array of strings.
  answer: z.union([z.string().max(1000), z.array(z.string().max(200)).max(12)]),
});

export const ClarifyRequestSchema = z.object({
  rawQuery: z.string().min(10).max(500),
});

/**
 * Policy guardrail decision. Runs before the clarifier — if a query
 * violates privacy norms, targets private individuals for scraping,
 * or would produce low-quality inferred data, the system refuses
 * with a reason and (where possible) reframe suggestions.
 *
 * Fail-open: on model error the backend returns {decision:'allow'}
 * with no reason. Refusal is an explicit AI judgment, not a fallback.
 */
export const POLICY_DECISIONS = ['allow', 'refuse'] as const;

export const POLICY_REFUSAL_CATEGORIES = [
  'privacy',     // personal contact harvesting without consent
  'sensitive',   // health / religion / politics / sexuality targeting
  'stalking',    // tracking a private individual's location / behavior
  'low_quality', // inferred-interest on private individuals — unreliable fiction
  'unsupported', // legitimate intent but out of the product's scope
] as const;

/**
 * Tolerant of the model inventing allow-side labels. In practice the guardrail
 * sometimes returns e.g. `category: 'organization_discovery'` on an allow
 * decision — that's not a refusal category and would otherwise fail schema
 * validation and force fail-open. Treat unknown category strings as "no
 * category" so the decision itself still parses. Valid refusal categories
 * are preserved verbatim.
 */
export const PolicyDecisionSchema = z.preprocess(
  (val) => {
    if (typeof val !== 'object' || val === null) return val;
    const obj = val as Record<string, unknown>;
    const validCategories = POLICY_REFUSAL_CATEGORIES as readonly string[];
    if (typeof obj.category === 'string' && !validCategories.includes(obj.category)) {
      return { ...obj, category: undefined };
    }
    return obj;
  },
  z.object({
    decision: z.enum(POLICY_DECISIONS),
    category: z.enum(POLICY_REFUSAL_CATEGORIES).optional(),
    reason: z.string().max(800).optional(),
    /** Reframes the user could try — usually 2-3 concrete alternatives. */
    suggestions: z.array(z.string().min(5).max(300)).max(5).optional(),
  }),
);

export type PolicyDecision = z.infer<typeof PolicyDecisionSchema>;

export const ClarifyResponseSchema = z.object({
  policy: PolicyDecisionSchema,
  questions: z.array(ClarificationQuestionSchema).max(8),
});

export const CreateJobSchema = z.object({
  rawQuery: z.string().min(10).max(500),
  // Optional — API clients can skip the clarify round-trip if they already
  // have a high-confidence query. The wizard UI always provides it.
  clarifications: z.array(ClarificationAnswerSchema).max(8).optional(),
});

export type ClarificationQuestionType = z.infer<typeof ClarificationQuestionTypeSchema>;
export type ClarificationQuestion = z.infer<typeof ClarificationQuestionSchema>;
export type ClarificationAnswer = z.infer<typeof ClarificationAnswerSchema>;
export type ClarifyRequest = z.infer<typeof ClarifyRequestSchema>;
export type ClarifyResponse = z.infer<typeof ClarifyResponseSchema>;

/**
 * Supported fact types. The UI formatter and CSV exporter both key off this.
 * Keep conservative — every new type requires corresponding UI handling.
 *   - text         : freeform short string
 *   - number       : unitless numeric (headcount, employees, etc.)
 *   - currency     : monetary amount — pair with { unit: "USD" | "NGN" | ... }
 *   - percentage   : 0-100 or 0-1 numeric with % suffix
 *   - date         : ISO date string (YYYY-MM-DD) or ISO datetime
 *   - url          : absolute URL, rendered as link
 *   - email        : email address, rendered with mailto:
 *   - phone        : phone number, rendered with tel:
 *   - tags         : short string array, rendered as chip list
 */
export const FactTypeSchema = z.enum([
  'text', 'number', 'currency', 'percentage',
  'date', 'url', 'email', 'phone', 'tags',
]);

/**
 * A single column the user asked for in their query output. Multiple columns
 * together form the `outputSchema` on ParsedIntent.
 *
 * `key` is a stable lowercase snake_case slug used as the map key in
 * `Lead.facts`. `label` is the human header. `type` drives UI formatting.
 * `required` controls whether leads missing this fact are flagged
 * "incomplete" on the UI (they are still written).
 */
export const OutputSchemaColumnSchema = z.object({
  key: z.string().regex(/^[a-z][a-z0-9_]*$/, 'must be lowercase snake_case'),
  label: z.string().min(1).max(80),
  type: FactTypeSchema.default('text'),
  description: z.string().max(200).optional(),
  required: z.boolean().default(false),
});

export const ParsedIntentSchema = z.object({
  // Nullable: for named-entity / contact-lookup queries ("anyone at Acme Corp") the
  // industry is unknowable from the query text alone — enrichment fills it in later.
  industry: z.string().nullish(),
  subIndustry: z.string().nullish(),
  geography: z.object({
    country: z.string().nullish(),
    state: z.string().nullish(),
    city: z.string().nullish(),
  }),
  targetCount: z.number().int().min(1).max(1000).default(50),
  desiredFields: z.array(z.enum(DESIRED_FIELDS)).default(['businessEmail']),
  companySize: z.string().nullish(),
  keywords: z.array(z.string()).default([]),
  confidenceScore: z.number().min(0).max(1).default(0.8),
  queryType: z.enum(['named_entity_list', 'demographic_filter', 'contact_lookup']).default('demographic_filter'),
  namedEntities: z.array(z.string()).nullable().default(null),
  /**
   * Extra columns the user asked for beyond the standard contact fields.
   * e.g. "top 20 fintechs with funding info" → [{key:"amount_raised",...},
   * {key:"funding_round",...}]. Empty array when the query asks only for
   * standard fields. Agent fills in `Lead.facts[key]` when it finds values.
   */
  outputSchema: z.array(OutputSchemaColumnSchema).default([]),
  userOffering: z.string().nullish(),
  /**
   * Industries / sectors that would BUY the user's offering. Populated
   * by the parser when `userOffering` is set, derived from "what kinds
   * of businesses need this service?". Discovery query builders read
   * this instead of `keywords` (which describe the user's offering, not
   * the target buyers) so we don't search for the user's competitors.
   *
   * Example: userOffering="travel agency services for staff bookings"
   * → targetBuyerIndustries = ["oil & gas", "consulting", "NGOs",
   *   "manufacturing", "construction", "education", "multinationals"]
   *
   * Null when no offering is stated or buyer-industries can't be inferred.
   */
  targetBuyerIndustries: z.array(z.string()).nullable().default(null),
  /**
   * When true, discovery actively filters out well-known / household-name
   * companies. Set by the parser when the brief uses cues like "small",
   * "not big", "not popular", "household names", "lesser-known", "upcoming",
   * "under-the-radar". Maps discovery filters by review-count threshold;
   * the LLM-recall prompt has a separate retrieval-bias rule that triggers
   * regardless of this flag.
   */
  excludeWellKnown: z.boolean().default(false),
});

/** A single fact value attached to a lead, keyed under Lead.facts. */
export const FactValueSchema = z.object({
  /** The actual value. Type depends on the paired outputSchema column. */
  value: z.union([z.string(), z.number(), z.boolean(), z.array(z.string())]).nullable(),
  /** Optional unit hint (e.g. "USD", "NGN" for currency; "employees" for number). */
  unit: z.string().optional(),
  /** Where we learned this — required when method implies a URL. */
  sourceUrl: z.string().url().optional(),
  /** 0-1 confidence. Distinct from lead rankScore. */
  confidence: z.number().min(0).max(1).optional(),
  /** Original raw text snippet, useful for debugging / audit. */
  raw: z.string().max(500).optional(),
});

export type CreateJobInput = z.infer<typeof CreateJobSchema>;
export type ParsedIntentOutput = z.infer<typeof ParsedIntentSchema>;
export type FactType = z.infer<typeof FactTypeSchema>;
export type OutputSchemaColumn = z.infer<typeof OutputSchemaColumnSchema>;
export type FactValue = z.infer<typeof FactValueSchema>;
